<html>
<body>
報告被周圍的 catch 塊禁止的 <code>assert</code> 語句和測試框架斷言。
此類別斷言永遠不會失敗，因為將捕獲並無提示地忽略拋出的 <code>AssertionError</code>。
<p><b>範例 1：</b></p>
<pre><code>
  void javaAssertion() {
    try {
      ...
      assert 1 == 2;
    } catch (AssertionError e) {
      // 該斷言被無提示地忽略
    }
  }
</code></pre>
<p><b>範例 2：</b></p>
<pre><code>
  @Test
  void testWithAssertJ() {
    try {
      ...
      assertThat(1).as("test").isEqualTo(2);
    } catch (AssertionError e) {
      // 該斷言被無提示地忽略
    }
  }
</code></pre>
<p><b>範例 3：</b></p>
<pre><code>
  @Test
  void testWithJunit() {
    try {
      ...
      assertEquals(1, 2);
    } catch (AssertionError e) {
      // 該斷言被無提示地忽略
    }
  }
</code></pre>
<!-- tooltip end -->
<p><small>2020.3 最新變化</small></p>
</body>
</html>