<html>
<body>
報告使用 catch 塊屏蔽的斷言語句和測試框架斷言。
此類斷言永遠不會失敗，因為將捕獲並無提示地忽略 <code>AssertionError</code>。
<p><b>範例 1：</b></p>
<pre><code>
void javaAssertion() {
  try {
    ...
    assert 1 == 2; // 斷言被無提示忽略
  } catch (AssertionError e) {}
}
</code></pre>
<p><b>範例 2：</b></p>
<pre><code>
@Test
void testWithAssertJ() {
  try {
    ...
    assertThat(1).as("test").isEqualTo(2); // 斷言被無提示忽略
  } catch (AssertionError e) {}
}
</code></pre>
<p><b>範例 3：</b></p>
<pre><code>
@Test
void testWithJunit() {
  try {
    ...
    assertEquals(1, 2); // 斷言被無提示忽略
  } catch (AssertionError e) {}
}
</code></pre>
<!-- tooltip end -->
<p><small>2020.3 最新變化</small></p>
</body>
</html>